version: '3.3'
services:
  server:
    build: server
    deploy:
      replicas: 3
      mode: replicated
      endpoint_mode: vip
    restart: always
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_HOSTNAME: mariadb
      JWT_SECRET: mysecret123
      PASSWORD_SALT: mypasswordsalt
    links:
      - mariadb
    depends_on:
      - mariadb
  message-service:
    build: message-service
    ports:
      - 8081:8080
    environment:
      - PORT=8080
    restart: always
    links:
      - server
    depends_on:
      - server
    networks:
      - loadbalancing

  mariadb:
    build: db
    restart: always
    environment:
      MARIADB_DATABASE: mariadb
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: rootpass
    networks:
      - loadbalancing

  nginx:
    build: nginx-load-balancer
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: mariadb

networks:
  loadbalancing:
    