version: '3.3'
services:
  backend:
    build: server
    deploy:
      replicas: 3
      mode: replicated
      endpoint_mode: vip
    restart: always
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_HOSTNAME: mariadb
      JWT_SECRET: mysecret123
      PASSWORD_SALT: mypasswordsalt
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - loadbalancing

  message-service:
    build: message-service
    deploy:
      replicas: 3
      mode: replicated
      endpoint_mode: vip
    environment:
      - PORT=8081
    restart: always
    networks:
      - loadbalancing
  
  frontend:
    build: client
    deploy:
      replicas: 3
      mode: replicated
      endpoint_mode: vip
    restart: always
    networks:
      - loadbalancing

  mariadb:
    build: db
    restart: always
    environment:
      MARIADB_DATABASE: mariadb
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: rootpass
    networks:
      - loadbalancing
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 5

  nginx:
    build: nginx-load-balancer
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - backend
  mqtt-broker:
    build: mqtt
    ports:
      - "1883:1883"
    networks:
      - loadbalancing
    volumes:
      - ./mqtt:/mosquitto/config
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: mariadb
    networks:
      - loadbalancing

networks:
  loadbalancing:
    driver: bridge
    