version: '3.3'
services:
  server:
    build: server
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_HOSTNAME: mariadb
      JWT_SECRET: mysecret123
      PASSWORD_SALT: mypasswordsalt
    links:
      - mariadb
    depends_on:
      - mariadb
  mariadb:
    build: db
    restart: always
    environment:
      MARIADB_DATABASE: mariadb
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: rootpass
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: mariadb